// Automatically generated by MockGen. DO NOT EDIT!
// Source: vendor/github.com/aws/aws-sdk-go/service/autoscaling/autoscalingiface/interface.go

package mock

import (
	request "github.com/aws/aws-sdk-go/aws/request"
	autoscaling "github.com/aws/aws-sdk-go/service/autoscaling"
	gomock "github.com/golang/mock/gomock"
)

// Mock of AutoScalingAPI interface
type MockAutoScalingAPI struct {
	ctrl     *gomock.Controller
	recorder *_MockAutoScalingAPIRecorder
}

// Recorder for MockAutoScalingAPI (not exported)
type _MockAutoScalingAPIRecorder struct {
	mock *MockAutoScalingAPI
}

func NewMockAutoScalingAPI(ctrl *gomock.Controller) *MockAutoScalingAPI {
	mock := &MockAutoScalingAPI{ctrl: ctrl}
	mock.recorder = &_MockAutoScalingAPIRecorder{mock}
	return mock
}

func (_m *MockAutoScalingAPI) EXPECT() *_MockAutoScalingAPIRecorder {
	return _m.recorder
}

func (_m *MockAutoScalingAPI) AttachInstancesRequest(_param0 *autoscaling.AttachInstancesInput) (*request.Request, *autoscaling.AttachInstancesOutput) {
	ret := _m.ctrl.Call(_m, "AttachInstancesRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.AttachInstancesOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) AttachInstancesRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "AttachInstancesRequest", arg0)
}

func (_m *MockAutoScalingAPI) AttachInstances(_param0 *autoscaling.AttachInstancesInput) (*autoscaling.AttachInstancesOutput, error) {
	ret := _m.ctrl.Call(_m, "AttachInstances", _param0)
	ret0, _ := ret[0].(*autoscaling.AttachInstancesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) AttachInstances(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "AttachInstances", arg0)
}

func (_m *MockAutoScalingAPI) AttachLoadBalancerTargetGroupsRequest(_param0 *autoscaling.AttachLoadBalancerTargetGroupsInput) (*request.Request, *autoscaling.AttachLoadBalancerTargetGroupsOutput) {
	ret := _m.ctrl.Call(_m, "AttachLoadBalancerTargetGroupsRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.AttachLoadBalancerTargetGroupsOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) AttachLoadBalancerTargetGroupsRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "AttachLoadBalancerTargetGroupsRequest", arg0)
}

func (_m *MockAutoScalingAPI) AttachLoadBalancerTargetGroups(_param0 *autoscaling.AttachLoadBalancerTargetGroupsInput) (*autoscaling.AttachLoadBalancerTargetGroupsOutput, error) {
	ret := _m.ctrl.Call(_m, "AttachLoadBalancerTargetGroups", _param0)
	ret0, _ := ret[0].(*autoscaling.AttachLoadBalancerTargetGroupsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) AttachLoadBalancerTargetGroups(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "AttachLoadBalancerTargetGroups", arg0)
}

func (_m *MockAutoScalingAPI) AttachLoadBalancersRequest(_param0 *autoscaling.AttachLoadBalancersInput) (*request.Request, *autoscaling.AttachLoadBalancersOutput) {
	ret := _m.ctrl.Call(_m, "AttachLoadBalancersRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.AttachLoadBalancersOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) AttachLoadBalancersRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "AttachLoadBalancersRequest", arg0)
}

func (_m *MockAutoScalingAPI) AttachLoadBalancers(_param0 *autoscaling.AttachLoadBalancersInput) (*autoscaling.AttachLoadBalancersOutput, error) {
	ret := _m.ctrl.Call(_m, "AttachLoadBalancers", _param0)
	ret0, _ := ret[0].(*autoscaling.AttachLoadBalancersOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) AttachLoadBalancers(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "AttachLoadBalancers", arg0)
}

func (_m *MockAutoScalingAPI) CompleteLifecycleActionRequest(_param0 *autoscaling.CompleteLifecycleActionInput) (*request.Request, *autoscaling.CompleteLifecycleActionOutput) {
	ret := _m.ctrl.Call(_m, "CompleteLifecycleActionRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.CompleteLifecycleActionOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) CompleteLifecycleActionRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CompleteLifecycleActionRequest", arg0)
}

func (_m *MockAutoScalingAPI) CompleteLifecycleAction(_param0 *autoscaling.CompleteLifecycleActionInput) (*autoscaling.CompleteLifecycleActionOutput, error) {
	ret := _m.ctrl.Call(_m, "CompleteLifecycleAction", _param0)
	ret0, _ := ret[0].(*autoscaling.CompleteLifecycleActionOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) CompleteLifecycleAction(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CompleteLifecycleAction", arg0)
}

func (_m *MockAutoScalingAPI) CreateAutoScalingGroupRequest(_param0 *autoscaling.CreateAutoScalingGroupInput) (*request.Request, *autoscaling.CreateAutoScalingGroupOutput) {
	ret := _m.ctrl.Call(_m, "CreateAutoScalingGroupRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.CreateAutoScalingGroupOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) CreateAutoScalingGroupRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CreateAutoScalingGroupRequest", arg0)
}

func (_m *MockAutoScalingAPI) CreateAutoScalingGroup(_param0 *autoscaling.CreateAutoScalingGroupInput) (*autoscaling.CreateAutoScalingGroupOutput, error) {
	ret := _m.ctrl.Call(_m, "CreateAutoScalingGroup", _param0)
	ret0, _ := ret[0].(*autoscaling.CreateAutoScalingGroupOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) CreateAutoScalingGroup(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CreateAutoScalingGroup", arg0)
}

func (_m *MockAutoScalingAPI) CreateLaunchConfigurationRequest(_param0 *autoscaling.CreateLaunchConfigurationInput) (*request.Request, *autoscaling.CreateLaunchConfigurationOutput) {
	ret := _m.ctrl.Call(_m, "CreateLaunchConfigurationRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.CreateLaunchConfigurationOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) CreateLaunchConfigurationRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CreateLaunchConfigurationRequest", arg0)
}

func (_m *MockAutoScalingAPI) CreateLaunchConfiguration(_param0 *autoscaling.CreateLaunchConfigurationInput) (*autoscaling.CreateLaunchConfigurationOutput, error) {
	ret := _m.ctrl.Call(_m, "CreateLaunchConfiguration", _param0)
	ret0, _ := ret[0].(*autoscaling.CreateLaunchConfigurationOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) CreateLaunchConfiguration(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CreateLaunchConfiguration", arg0)
}

func (_m *MockAutoScalingAPI) CreateOrUpdateTagsRequest(_param0 *autoscaling.CreateOrUpdateTagsInput) (*request.Request, *autoscaling.CreateOrUpdateTagsOutput) {
	ret := _m.ctrl.Call(_m, "CreateOrUpdateTagsRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.CreateOrUpdateTagsOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) CreateOrUpdateTagsRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CreateOrUpdateTagsRequest", arg0)
}

func (_m *MockAutoScalingAPI) CreateOrUpdateTags(_param0 *autoscaling.CreateOrUpdateTagsInput) (*autoscaling.CreateOrUpdateTagsOutput, error) {
	ret := _m.ctrl.Call(_m, "CreateOrUpdateTags", _param0)
	ret0, _ := ret[0].(*autoscaling.CreateOrUpdateTagsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) CreateOrUpdateTags(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CreateOrUpdateTags", arg0)
}

func (_m *MockAutoScalingAPI) DeleteAutoScalingGroupRequest(_param0 *autoscaling.DeleteAutoScalingGroupInput) (*request.Request, *autoscaling.DeleteAutoScalingGroupOutput) {
	ret := _m.ctrl.Call(_m, "DeleteAutoScalingGroupRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.DeleteAutoScalingGroupOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DeleteAutoScalingGroupRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DeleteAutoScalingGroupRequest", arg0)
}

func (_m *MockAutoScalingAPI) DeleteAutoScalingGroup(_param0 *autoscaling.DeleteAutoScalingGroupInput) (*autoscaling.DeleteAutoScalingGroupOutput, error) {
	ret := _m.ctrl.Call(_m, "DeleteAutoScalingGroup", _param0)
	ret0, _ := ret[0].(*autoscaling.DeleteAutoScalingGroupOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DeleteAutoScalingGroup(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DeleteAutoScalingGroup", arg0)
}

func (_m *MockAutoScalingAPI) DeleteLaunchConfigurationRequest(_param0 *autoscaling.DeleteLaunchConfigurationInput) (*request.Request, *autoscaling.DeleteLaunchConfigurationOutput) {
	ret := _m.ctrl.Call(_m, "DeleteLaunchConfigurationRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.DeleteLaunchConfigurationOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DeleteLaunchConfigurationRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DeleteLaunchConfigurationRequest", arg0)
}

func (_m *MockAutoScalingAPI) DeleteLaunchConfiguration(_param0 *autoscaling.DeleteLaunchConfigurationInput) (*autoscaling.DeleteLaunchConfigurationOutput, error) {
	ret := _m.ctrl.Call(_m, "DeleteLaunchConfiguration", _param0)
	ret0, _ := ret[0].(*autoscaling.DeleteLaunchConfigurationOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DeleteLaunchConfiguration(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DeleteLaunchConfiguration", arg0)
}

func (_m *MockAutoScalingAPI) DeleteLifecycleHookRequest(_param0 *autoscaling.DeleteLifecycleHookInput) (*request.Request, *autoscaling.DeleteLifecycleHookOutput) {
	ret := _m.ctrl.Call(_m, "DeleteLifecycleHookRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.DeleteLifecycleHookOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DeleteLifecycleHookRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DeleteLifecycleHookRequest", arg0)
}

func (_m *MockAutoScalingAPI) DeleteLifecycleHook(_param0 *autoscaling.DeleteLifecycleHookInput) (*autoscaling.DeleteLifecycleHookOutput, error) {
	ret := _m.ctrl.Call(_m, "DeleteLifecycleHook", _param0)
	ret0, _ := ret[0].(*autoscaling.DeleteLifecycleHookOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DeleteLifecycleHook(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DeleteLifecycleHook", arg0)
}

func (_m *MockAutoScalingAPI) DeleteNotificationConfigurationRequest(_param0 *autoscaling.DeleteNotificationConfigurationInput) (*request.Request, *autoscaling.DeleteNotificationConfigurationOutput) {
	ret := _m.ctrl.Call(_m, "DeleteNotificationConfigurationRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.DeleteNotificationConfigurationOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DeleteNotificationConfigurationRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DeleteNotificationConfigurationRequest", arg0)
}

func (_m *MockAutoScalingAPI) DeleteNotificationConfiguration(_param0 *autoscaling.DeleteNotificationConfigurationInput) (*autoscaling.DeleteNotificationConfigurationOutput, error) {
	ret := _m.ctrl.Call(_m, "DeleteNotificationConfiguration", _param0)
	ret0, _ := ret[0].(*autoscaling.DeleteNotificationConfigurationOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DeleteNotificationConfiguration(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DeleteNotificationConfiguration", arg0)
}

func (_m *MockAutoScalingAPI) DeletePolicyRequest(_param0 *autoscaling.DeletePolicyInput) (*request.Request, *autoscaling.DeletePolicyOutput) {
	ret := _m.ctrl.Call(_m, "DeletePolicyRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.DeletePolicyOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DeletePolicyRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DeletePolicyRequest", arg0)
}

func (_m *MockAutoScalingAPI) DeletePolicy(_param0 *autoscaling.DeletePolicyInput) (*autoscaling.DeletePolicyOutput, error) {
	ret := _m.ctrl.Call(_m, "DeletePolicy", _param0)
	ret0, _ := ret[0].(*autoscaling.DeletePolicyOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DeletePolicy(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DeletePolicy", arg0)
}

func (_m *MockAutoScalingAPI) DeleteScheduledActionRequest(_param0 *autoscaling.DeleteScheduledActionInput) (*request.Request, *autoscaling.DeleteScheduledActionOutput) {
	ret := _m.ctrl.Call(_m, "DeleteScheduledActionRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.DeleteScheduledActionOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DeleteScheduledActionRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DeleteScheduledActionRequest", arg0)
}

func (_m *MockAutoScalingAPI) DeleteScheduledAction(_param0 *autoscaling.DeleteScheduledActionInput) (*autoscaling.DeleteScheduledActionOutput, error) {
	ret := _m.ctrl.Call(_m, "DeleteScheduledAction", _param0)
	ret0, _ := ret[0].(*autoscaling.DeleteScheduledActionOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DeleteScheduledAction(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DeleteScheduledAction", arg0)
}

func (_m *MockAutoScalingAPI) DeleteTagsRequest(_param0 *autoscaling.DeleteTagsInput) (*request.Request, *autoscaling.DeleteTagsOutput) {
	ret := _m.ctrl.Call(_m, "DeleteTagsRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.DeleteTagsOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DeleteTagsRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DeleteTagsRequest", arg0)
}

func (_m *MockAutoScalingAPI) DeleteTags(_param0 *autoscaling.DeleteTagsInput) (*autoscaling.DeleteTagsOutput, error) {
	ret := _m.ctrl.Call(_m, "DeleteTags", _param0)
	ret0, _ := ret[0].(*autoscaling.DeleteTagsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DeleteTags(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DeleteTags", arg0)
}

func (_m *MockAutoScalingAPI) DescribeAccountLimitsRequest(_param0 *autoscaling.DescribeAccountLimitsInput) (*request.Request, *autoscaling.DescribeAccountLimitsOutput) {
	ret := _m.ctrl.Call(_m, "DescribeAccountLimitsRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.DescribeAccountLimitsOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DescribeAccountLimitsRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DescribeAccountLimitsRequest", arg0)
}

func (_m *MockAutoScalingAPI) DescribeAccountLimits(_param0 *autoscaling.DescribeAccountLimitsInput) (*autoscaling.DescribeAccountLimitsOutput, error) {
	ret := _m.ctrl.Call(_m, "DescribeAccountLimits", _param0)
	ret0, _ := ret[0].(*autoscaling.DescribeAccountLimitsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DescribeAccountLimits(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DescribeAccountLimits", arg0)
}

func (_m *MockAutoScalingAPI) DescribeAdjustmentTypesRequest(_param0 *autoscaling.DescribeAdjustmentTypesInput) (*request.Request, *autoscaling.DescribeAdjustmentTypesOutput) {
	ret := _m.ctrl.Call(_m, "DescribeAdjustmentTypesRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.DescribeAdjustmentTypesOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DescribeAdjustmentTypesRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DescribeAdjustmentTypesRequest", arg0)
}

func (_m *MockAutoScalingAPI) DescribeAdjustmentTypes(_param0 *autoscaling.DescribeAdjustmentTypesInput) (*autoscaling.DescribeAdjustmentTypesOutput, error) {
	ret := _m.ctrl.Call(_m, "DescribeAdjustmentTypes", _param0)
	ret0, _ := ret[0].(*autoscaling.DescribeAdjustmentTypesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DescribeAdjustmentTypes(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DescribeAdjustmentTypes", arg0)
}

func (_m *MockAutoScalingAPI) DescribeAutoScalingGroupsRequest(_param0 *autoscaling.DescribeAutoScalingGroupsInput) (*request.Request, *autoscaling.DescribeAutoScalingGroupsOutput) {
	ret := _m.ctrl.Call(_m, "DescribeAutoScalingGroupsRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.DescribeAutoScalingGroupsOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DescribeAutoScalingGroupsRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DescribeAutoScalingGroupsRequest", arg0)
}

func (_m *MockAutoScalingAPI) DescribeAutoScalingGroups(_param0 *autoscaling.DescribeAutoScalingGroupsInput) (*autoscaling.DescribeAutoScalingGroupsOutput, error) {
	ret := _m.ctrl.Call(_m, "DescribeAutoScalingGroups", _param0)
	ret0, _ := ret[0].(*autoscaling.DescribeAutoScalingGroupsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DescribeAutoScalingGroups(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DescribeAutoScalingGroups", arg0)
}

func (_m *MockAutoScalingAPI) DescribeAutoScalingGroupsPages(_param0 *autoscaling.DescribeAutoScalingGroupsInput, _param1 func(*autoscaling.DescribeAutoScalingGroupsOutput, bool) bool) error {
	ret := _m.ctrl.Call(_m, "DescribeAutoScalingGroupsPages", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockAutoScalingAPIRecorder) DescribeAutoScalingGroupsPages(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DescribeAutoScalingGroupsPages", arg0, arg1)
}

func (_m *MockAutoScalingAPI) DescribeAutoScalingInstancesRequest(_param0 *autoscaling.DescribeAutoScalingInstancesInput) (*request.Request, *autoscaling.DescribeAutoScalingInstancesOutput) {
	ret := _m.ctrl.Call(_m, "DescribeAutoScalingInstancesRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.DescribeAutoScalingInstancesOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DescribeAutoScalingInstancesRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DescribeAutoScalingInstancesRequest", arg0)
}

func (_m *MockAutoScalingAPI) DescribeAutoScalingInstances(_param0 *autoscaling.DescribeAutoScalingInstancesInput) (*autoscaling.DescribeAutoScalingInstancesOutput, error) {
	ret := _m.ctrl.Call(_m, "DescribeAutoScalingInstances", _param0)
	ret0, _ := ret[0].(*autoscaling.DescribeAutoScalingInstancesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DescribeAutoScalingInstances(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DescribeAutoScalingInstances", arg0)
}

func (_m *MockAutoScalingAPI) DescribeAutoScalingInstancesPages(_param0 *autoscaling.DescribeAutoScalingInstancesInput, _param1 func(*autoscaling.DescribeAutoScalingInstancesOutput, bool) bool) error {
	ret := _m.ctrl.Call(_m, "DescribeAutoScalingInstancesPages", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockAutoScalingAPIRecorder) DescribeAutoScalingInstancesPages(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DescribeAutoScalingInstancesPages", arg0, arg1)
}

func (_m *MockAutoScalingAPI) DescribeAutoScalingNotificationTypesRequest(_param0 *autoscaling.DescribeAutoScalingNotificationTypesInput) (*request.Request, *autoscaling.DescribeAutoScalingNotificationTypesOutput) {
	ret := _m.ctrl.Call(_m, "DescribeAutoScalingNotificationTypesRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.DescribeAutoScalingNotificationTypesOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DescribeAutoScalingNotificationTypesRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DescribeAutoScalingNotificationTypesRequest", arg0)
}

func (_m *MockAutoScalingAPI) DescribeAutoScalingNotificationTypes(_param0 *autoscaling.DescribeAutoScalingNotificationTypesInput) (*autoscaling.DescribeAutoScalingNotificationTypesOutput, error) {
	ret := _m.ctrl.Call(_m, "DescribeAutoScalingNotificationTypes", _param0)
	ret0, _ := ret[0].(*autoscaling.DescribeAutoScalingNotificationTypesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DescribeAutoScalingNotificationTypes(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DescribeAutoScalingNotificationTypes", arg0)
}

func (_m *MockAutoScalingAPI) DescribeLaunchConfigurationsRequest(_param0 *autoscaling.DescribeLaunchConfigurationsInput) (*request.Request, *autoscaling.DescribeLaunchConfigurationsOutput) {
	ret := _m.ctrl.Call(_m, "DescribeLaunchConfigurationsRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.DescribeLaunchConfigurationsOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DescribeLaunchConfigurationsRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DescribeLaunchConfigurationsRequest", arg0)
}

func (_m *MockAutoScalingAPI) DescribeLaunchConfigurations(_param0 *autoscaling.DescribeLaunchConfigurationsInput) (*autoscaling.DescribeLaunchConfigurationsOutput, error) {
	ret := _m.ctrl.Call(_m, "DescribeLaunchConfigurations", _param0)
	ret0, _ := ret[0].(*autoscaling.DescribeLaunchConfigurationsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DescribeLaunchConfigurations(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DescribeLaunchConfigurations", arg0)
}

func (_m *MockAutoScalingAPI) DescribeLaunchConfigurationsPages(_param0 *autoscaling.DescribeLaunchConfigurationsInput, _param1 func(*autoscaling.DescribeLaunchConfigurationsOutput, bool) bool) error {
	ret := _m.ctrl.Call(_m, "DescribeLaunchConfigurationsPages", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockAutoScalingAPIRecorder) DescribeLaunchConfigurationsPages(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DescribeLaunchConfigurationsPages", arg0, arg1)
}

func (_m *MockAutoScalingAPI) DescribeLifecycleHookTypesRequest(_param0 *autoscaling.DescribeLifecycleHookTypesInput) (*request.Request, *autoscaling.DescribeLifecycleHookTypesOutput) {
	ret := _m.ctrl.Call(_m, "DescribeLifecycleHookTypesRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.DescribeLifecycleHookTypesOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DescribeLifecycleHookTypesRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DescribeLifecycleHookTypesRequest", arg0)
}

func (_m *MockAutoScalingAPI) DescribeLifecycleHookTypes(_param0 *autoscaling.DescribeLifecycleHookTypesInput) (*autoscaling.DescribeLifecycleHookTypesOutput, error) {
	ret := _m.ctrl.Call(_m, "DescribeLifecycleHookTypes", _param0)
	ret0, _ := ret[0].(*autoscaling.DescribeLifecycleHookTypesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DescribeLifecycleHookTypes(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DescribeLifecycleHookTypes", arg0)
}

func (_m *MockAutoScalingAPI) DescribeLifecycleHooksRequest(_param0 *autoscaling.DescribeLifecycleHooksInput) (*request.Request, *autoscaling.DescribeLifecycleHooksOutput) {
	ret := _m.ctrl.Call(_m, "DescribeLifecycleHooksRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.DescribeLifecycleHooksOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DescribeLifecycleHooksRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DescribeLifecycleHooksRequest", arg0)
}

func (_m *MockAutoScalingAPI) DescribeLifecycleHooks(_param0 *autoscaling.DescribeLifecycleHooksInput) (*autoscaling.DescribeLifecycleHooksOutput, error) {
	ret := _m.ctrl.Call(_m, "DescribeLifecycleHooks", _param0)
	ret0, _ := ret[0].(*autoscaling.DescribeLifecycleHooksOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DescribeLifecycleHooks(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DescribeLifecycleHooks", arg0)
}

func (_m *MockAutoScalingAPI) DescribeLoadBalancerTargetGroupsRequest(_param0 *autoscaling.DescribeLoadBalancerTargetGroupsInput) (*request.Request, *autoscaling.DescribeLoadBalancerTargetGroupsOutput) {
	ret := _m.ctrl.Call(_m, "DescribeLoadBalancerTargetGroupsRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.DescribeLoadBalancerTargetGroupsOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DescribeLoadBalancerTargetGroupsRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DescribeLoadBalancerTargetGroupsRequest", arg0)
}

func (_m *MockAutoScalingAPI) DescribeLoadBalancerTargetGroups(_param0 *autoscaling.DescribeLoadBalancerTargetGroupsInput) (*autoscaling.DescribeLoadBalancerTargetGroupsOutput, error) {
	ret := _m.ctrl.Call(_m, "DescribeLoadBalancerTargetGroups", _param0)
	ret0, _ := ret[0].(*autoscaling.DescribeLoadBalancerTargetGroupsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DescribeLoadBalancerTargetGroups(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DescribeLoadBalancerTargetGroups", arg0)
}

func (_m *MockAutoScalingAPI) DescribeLoadBalancersRequest(_param0 *autoscaling.DescribeLoadBalancersInput) (*request.Request, *autoscaling.DescribeLoadBalancersOutput) {
	ret := _m.ctrl.Call(_m, "DescribeLoadBalancersRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.DescribeLoadBalancersOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DescribeLoadBalancersRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DescribeLoadBalancersRequest", arg0)
}

func (_m *MockAutoScalingAPI) DescribeLoadBalancers(_param0 *autoscaling.DescribeLoadBalancersInput) (*autoscaling.DescribeLoadBalancersOutput, error) {
	ret := _m.ctrl.Call(_m, "DescribeLoadBalancers", _param0)
	ret0, _ := ret[0].(*autoscaling.DescribeLoadBalancersOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DescribeLoadBalancers(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DescribeLoadBalancers", arg0)
}

func (_m *MockAutoScalingAPI) DescribeMetricCollectionTypesRequest(_param0 *autoscaling.DescribeMetricCollectionTypesInput) (*request.Request, *autoscaling.DescribeMetricCollectionTypesOutput) {
	ret := _m.ctrl.Call(_m, "DescribeMetricCollectionTypesRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.DescribeMetricCollectionTypesOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DescribeMetricCollectionTypesRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DescribeMetricCollectionTypesRequest", arg0)
}

func (_m *MockAutoScalingAPI) DescribeMetricCollectionTypes(_param0 *autoscaling.DescribeMetricCollectionTypesInput) (*autoscaling.DescribeMetricCollectionTypesOutput, error) {
	ret := _m.ctrl.Call(_m, "DescribeMetricCollectionTypes", _param0)
	ret0, _ := ret[0].(*autoscaling.DescribeMetricCollectionTypesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DescribeMetricCollectionTypes(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DescribeMetricCollectionTypes", arg0)
}

func (_m *MockAutoScalingAPI) DescribeNotificationConfigurationsRequest(_param0 *autoscaling.DescribeNotificationConfigurationsInput) (*request.Request, *autoscaling.DescribeNotificationConfigurationsOutput) {
	ret := _m.ctrl.Call(_m, "DescribeNotificationConfigurationsRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.DescribeNotificationConfigurationsOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DescribeNotificationConfigurationsRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DescribeNotificationConfigurationsRequest", arg0)
}

func (_m *MockAutoScalingAPI) DescribeNotificationConfigurations(_param0 *autoscaling.DescribeNotificationConfigurationsInput) (*autoscaling.DescribeNotificationConfigurationsOutput, error) {
	ret := _m.ctrl.Call(_m, "DescribeNotificationConfigurations", _param0)
	ret0, _ := ret[0].(*autoscaling.DescribeNotificationConfigurationsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DescribeNotificationConfigurations(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DescribeNotificationConfigurations", arg0)
}

func (_m *MockAutoScalingAPI) DescribeNotificationConfigurationsPages(_param0 *autoscaling.DescribeNotificationConfigurationsInput, _param1 func(*autoscaling.DescribeNotificationConfigurationsOutput, bool) bool) error {
	ret := _m.ctrl.Call(_m, "DescribeNotificationConfigurationsPages", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockAutoScalingAPIRecorder) DescribeNotificationConfigurationsPages(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DescribeNotificationConfigurationsPages", arg0, arg1)
}

func (_m *MockAutoScalingAPI) DescribePoliciesRequest(_param0 *autoscaling.DescribePoliciesInput) (*request.Request, *autoscaling.DescribePoliciesOutput) {
	ret := _m.ctrl.Call(_m, "DescribePoliciesRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.DescribePoliciesOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DescribePoliciesRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DescribePoliciesRequest", arg0)
}

func (_m *MockAutoScalingAPI) DescribePolicies(_param0 *autoscaling.DescribePoliciesInput) (*autoscaling.DescribePoliciesOutput, error) {
	ret := _m.ctrl.Call(_m, "DescribePolicies", _param0)
	ret0, _ := ret[0].(*autoscaling.DescribePoliciesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DescribePolicies(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DescribePolicies", arg0)
}

func (_m *MockAutoScalingAPI) DescribePoliciesPages(_param0 *autoscaling.DescribePoliciesInput, _param1 func(*autoscaling.DescribePoliciesOutput, bool) bool) error {
	ret := _m.ctrl.Call(_m, "DescribePoliciesPages", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockAutoScalingAPIRecorder) DescribePoliciesPages(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DescribePoliciesPages", arg0, arg1)
}

func (_m *MockAutoScalingAPI) DescribeScalingActivitiesRequest(_param0 *autoscaling.DescribeScalingActivitiesInput) (*request.Request, *autoscaling.DescribeScalingActivitiesOutput) {
	ret := _m.ctrl.Call(_m, "DescribeScalingActivitiesRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.DescribeScalingActivitiesOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DescribeScalingActivitiesRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DescribeScalingActivitiesRequest", arg0)
}

func (_m *MockAutoScalingAPI) DescribeScalingActivities(_param0 *autoscaling.DescribeScalingActivitiesInput) (*autoscaling.DescribeScalingActivitiesOutput, error) {
	ret := _m.ctrl.Call(_m, "DescribeScalingActivities", _param0)
	ret0, _ := ret[0].(*autoscaling.DescribeScalingActivitiesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DescribeScalingActivities(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DescribeScalingActivities", arg0)
}

func (_m *MockAutoScalingAPI) DescribeScalingActivitiesPages(_param0 *autoscaling.DescribeScalingActivitiesInput, _param1 func(*autoscaling.DescribeScalingActivitiesOutput, bool) bool) error {
	ret := _m.ctrl.Call(_m, "DescribeScalingActivitiesPages", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockAutoScalingAPIRecorder) DescribeScalingActivitiesPages(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DescribeScalingActivitiesPages", arg0, arg1)
}

func (_m *MockAutoScalingAPI) DescribeScalingProcessTypesRequest(_param0 *autoscaling.DescribeScalingProcessTypesInput) (*request.Request, *autoscaling.DescribeScalingProcessTypesOutput) {
	ret := _m.ctrl.Call(_m, "DescribeScalingProcessTypesRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.DescribeScalingProcessTypesOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DescribeScalingProcessTypesRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DescribeScalingProcessTypesRequest", arg0)
}

func (_m *MockAutoScalingAPI) DescribeScalingProcessTypes(_param0 *autoscaling.DescribeScalingProcessTypesInput) (*autoscaling.DescribeScalingProcessTypesOutput, error) {
	ret := _m.ctrl.Call(_m, "DescribeScalingProcessTypes", _param0)
	ret0, _ := ret[0].(*autoscaling.DescribeScalingProcessTypesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DescribeScalingProcessTypes(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DescribeScalingProcessTypes", arg0)
}

func (_m *MockAutoScalingAPI) DescribeScheduledActionsRequest(_param0 *autoscaling.DescribeScheduledActionsInput) (*request.Request, *autoscaling.DescribeScheduledActionsOutput) {
	ret := _m.ctrl.Call(_m, "DescribeScheduledActionsRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.DescribeScheduledActionsOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DescribeScheduledActionsRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DescribeScheduledActionsRequest", arg0)
}

func (_m *MockAutoScalingAPI) DescribeScheduledActions(_param0 *autoscaling.DescribeScheduledActionsInput) (*autoscaling.DescribeScheduledActionsOutput, error) {
	ret := _m.ctrl.Call(_m, "DescribeScheduledActions", _param0)
	ret0, _ := ret[0].(*autoscaling.DescribeScheduledActionsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DescribeScheduledActions(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DescribeScheduledActions", arg0)
}

func (_m *MockAutoScalingAPI) DescribeScheduledActionsPages(_param0 *autoscaling.DescribeScheduledActionsInput, _param1 func(*autoscaling.DescribeScheduledActionsOutput, bool) bool) error {
	ret := _m.ctrl.Call(_m, "DescribeScheduledActionsPages", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockAutoScalingAPIRecorder) DescribeScheduledActionsPages(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DescribeScheduledActionsPages", arg0, arg1)
}

func (_m *MockAutoScalingAPI) DescribeTagsRequest(_param0 *autoscaling.DescribeTagsInput) (*request.Request, *autoscaling.DescribeTagsOutput) {
	ret := _m.ctrl.Call(_m, "DescribeTagsRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.DescribeTagsOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DescribeTagsRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DescribeTagsRequest", arg0)
}

func (_m *MockAutoScalingAPI) DescribeTags(_param0 *autoscaling.DescribeTagsInput) (*autoscaling.DescribeTagsOutput, error) {
	ret := _m.ctrl.Call(_m, "DescribeTags", _param0)
	ret0, _ := ret[0].(*autoscaling.DescribeTagsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DescribeTags(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DescribeTags", arg0)
}

func (_m *MockAutoScalingAPI) DescribeTagsPages(_param0 *autoscaling.DescribeTagsInput, _param1 func(*autoscaling.DescribeTagsOutput, bool) bool) error {
	ret := _m.ctrl.Call(_m, "DescribeTagsPages", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockAutoScalingAPIRecorder) DescribeTagsPages(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DescribeTagsPages", arg0, arg1)
}

func (_m *MockAutoScalingAPI) DescribeTerminationPolicyTypesRequest(_param0 *autoscaling.DescribeTerminationPolicyTypesInput) (*request.Request, *autoscaling.DescribeTerminationPolicyTypesOutput) {
	ret := _m.ctrl.Call(_m, "DescribeTerminationPolicyTypesRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.DescribeTerminationPolicyTypesOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DescribeTerminationPolicyTypesRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DescribeTerminationPolicyTypesRequest", arg0)
}

func (_m *MockAutoScalingAPI) DescribeTerminationPolicyTypes(_param0 *autoscaling.DescribeTerminationPolicyTypesInput) (*autoscaling.DescribeTerminationPolicyTypesOutput, error) {
	ret := _m.ctrl.Call(_m, "DescribeTerminationPolicyTypes", _param0)
	ret0, _ := ret[0].(*autoscaling.DescribeTerminationPolicyTypesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DescribeTerminationPolicyTypes(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DescribeTerminationPolicyTypes", arg0)
}

func (_m *MockAutoScalingAPI) DetachInstancesRequest(_param0 *autoscaling.DetachInstancesInput) (*request.Request, *autoscaling.DetachInstancesOutput) {
	ret := _m.ctrl.Call(_m, "DetachInstancesRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.DetachInstancesOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DetachInstancesRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DetachInstancesRequest", arg0)
}

func (_m *MockAutoScalingAPI) DetachInstances(_param0 *autoscaling.DetachInstancesInput) (*autoscaling.DetachInstancesOutput, error) {
	ret := _m.ctrl.Call(_m, "DetachInstances", _param0)
	ret0, _ := ret[0].(*autoscaling.DetachInstancesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DetachInstances(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DetachInstances", arg0)
}

func (_m *MockAutoScalingAPI) DetachLoadBalancerTargetGroupsRequest(_param0 *autoscaling.DetachLoadBalancerTargetGroupsInput) (*request.Request, *autoscaling.DetachLoadBalancerTargetGroupsOutput) {
	ret := _m.ctrl.Call(_m, "DetachLoadBalancerTargetGroupsRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.DetachLoadBalancerTargetGroupsOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DetachLoadBalancerTargetGroupsRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DetachLoadBalancerTargetGroupsRequest", arg0)
}

func (_m *MockAutoScalingAPI) DetachLoadBalancerTargetGroups(_param0 *autoscaling.DetachLoadBalancerTargetGroupsInput) (*autoscaling.DetachLoadBalancerTargetGroupsOutput, error) {
	ret := _m.ctrl.Call(_m, "DetachLoadBalancerTargetGroups", _param0)
	ret0, _ := ret[0].(*autoscaling.DetachLoadBalancerTargetGroupsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DetachLoadBalancerTargetGroups(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DetachLoadBalancerTargetGroups", arg0)
}

func (_m *MockAutoScalingAPI) DetachLoadBalancersRequest(_param0 *autoscaling.DetachLoadBalancersInput) (*request.Request, *autoscaling.DetachLoadBalancersOutput) {
	ret := _m.ctrl.Call(_m, "DetachLoadBalancersRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.DetachLoadBalancersOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DetachLoadBalancersRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DetachLoadBalancersRequest", arg0)
}

func (_m *MockAutoScalingAPI) DetachLoadBalancers(_param0 *autoscaling.DetachLoadBalancersInput) (*autoscaling.DetachLoadBalancersOutput, error) {
	ret := _m.ctrl.Call(_m, "DetachLoadBalancers", _param0)
	ret0, _ := ret[0].(*autoscaling.DetachLoadBalancersOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DetachLoadBalancers(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DetachLoadBalancers", arg0)
}

func (_m *MockAutoScalingAPI) DisableMetricsCollectionRequest(_param0 *autoscaling.DisableMetricsCollectionInput) (*request.Request, *autoscaling.DisableMetricsCollectionOutput) {
	ret := _m.ctrl.Call(_m, "DisableMetricsCollectionRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.DisableMetricsCollectionOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DisableMetricsCollectionRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DisableMetricsCollectionRequest", arg0)
}

func (_m *MockAutoScalingAPI) DisableMetricsCollection(_param0 *autoscaling.DisableMetricsCollectionInput) (*autoscaling.DisableMetricsCollectionOutput, error) {
	ret := _m.ctrl.Call(_m, "DisableMetricsCollection", _param0)
	ret0, _ := ret[0].(*autoscaling.DisableMetricsCollectionOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) DisableMetricsCollection(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DisableMetricsCollection", arg0)
}

func (_m *MockAutoScalingAPI) EnableMetricsCollectionRequest(_param0 *autoscaling.EnableMetricsCollectionInput) (*request.Request, *autoscaling.EnableMetricsCollectionOutput) {
	ret := _m.ctrl.Call(_m, "EnableMetricsCollectionRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.EnableMetricsCollectionOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) EnableMetricsCollectionRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "EnableMetricsCollectionRequest", arg0)
}

func (_m *MockAutoScalingAPI) EnableMetricsCollection(_param0 *autoscaling.EnableMetricsCollectionInput) (*autoscaling.EnableMetricsCollectionOutput, error) {
	ret := _m.ctrl.Call(_m, "EnableMetricsCollection", _param0)
	ret0, _ := ret[0].(*autoscaling.EnableMetricsCollectionOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) EnableMetricsCollection(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "EnableMetricsCollection", arg0)
}

func (_m *MockAutoScalingAPI) EnterStandbyRequest(_param0 *autoscaling.EnterStandbyInput) (*request.Request, *autoscaling.EnterStandbyOutput) {
	ret := _m.ctrl.Call(_m, "EnterStandbyRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.EnterStandbyOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) EnterStandbyRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "EnterStandbyRequest", arg0)
}

func (_m *MockAutoScalingAPI) EnterStandby(_param0 *autoscaling.EnterStandbyInput) (*autoscaling.EnterStandbyOutput, error) {
	ret := _m.ctrl.Call(_m, "EnterStandby", _param0)
	ret0, _ := ret[0].(*autoscaling.EnterStandbyOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) EnterStandby(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "EnterStandby", arg0)
}

func (_m *MockAutoScalingAPI) ExecutePolicyRequest(_param0 *autoscaling.ExecutePolicyInput) (*request.Request, *autoscaling.ExecutePolicyOutput) {
	ret := _m.ctrl.Call(_m, "ExecutePolicyRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.ExecutePolicyOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) ExecutePolicyRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ExecutePolicyRequest", arg0)
}

func (_m *MockAutoScalingAPI) ExecutePolicy(_param0 *autoscaling.ExecutePolicyInput) (*autoscaling.ExecutePolicyOutput, error) {
	ret := _m.ctrl.Call(_m, "ExecutePolicy", _param0)
	ret0, _ := ret[0].(*autoscaling.ExecutePolicyOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) ExecutePolicy(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ExecutePolicy", arg0)
}

func (_m *MockAutoScalingAPI) ExitStandbyRequest(_param0 *autoscaling.ExitStandbyInput) (*request.Request, *autoscaling.ExitStandbyOutput) {
	ret := _m.ctrl.Call(_m, "ExitStandbyRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.ExitStandbyOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) ExitStandbyRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ExitStandbyRequest", arg0)
}

func (_m *MockAutoScalingAPI) ExitStandby(_param0 *autoscaling.ExitStandbyInput) (*autoscaling.ExitStandbyOutput, error) {
	ret := _m.ctrl.Call(_m, "ExitStandby", _param0)
	ret0, _ := ret[0].(*autoscaling.ExitStandbyOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) ExitStandby(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ExitStandby", arg0)
}

func (_m *MockAutoScalingAPI) PutLifecycleHookRequest(_param0 *autoscaling.PutLifecycleHookInput) (*request.Request, *autoscaling.PutLifecycleHookOutput) {
	ret := _m.ctrl.Call(_m, "PutLifecycleHookRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.PutLifecycleHookOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) PutLifecycleHookRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "PutLifecycleHookRequest", arg0)
}

func (_m *MockAutoScalingAPI) PutLifecycleHook(_param0 *autoscaling.PutLifecycleHookInput) (*autoscaling.PutLifecycleHookOutput, error) {
	ret := _m.ctrl.Call(_m, "PutLifecycleHook", _param0)
	ret0, _ := ret[0].(*autoscaling.PutLifecycleHookOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) PutLifecycleHook(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "PutLifecycleHook", arg0)
}

func (_m *MockAutoScalingAPI) PutNotificationConfigurationRequest(_param0 *autoscaling.PutNotificationConfigurationInput) (*request.Request, *autoscaling.PutNotificationConfigurationOutput) {
	ret := _m.ctrl.Call(_m, "PutNotificationConfigurationRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.PutNotificationConfigurationOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) PutNotificationConfigurationRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "PutNotificationConfigurationRequest", arg0)
}

func (_m *MockAutoScalingAPI) PutNotificationConfiguration(_param0 *autoscaling.PutNotificationConfigurationInput) (*autoscaling.PutNotificationConfigurationOutput, error) {
	ret := _m.ctrl.Call(_m, "PutNotificationConfiguration", _param0)
	ret0, _ := ret[0].(*autoscaling.PutNotificationConfigurationOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) PutNotificationConfiguration(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "PutNotificationConfiguration", arg0)
}

func (_m *MockAutoScalingAPI) PutScalingPolicyRequest(_param0 *autoscaling.PutScalingPolicyInput) (*request.Request, *autoscaling.PutScalingPolicyOutput) {
	ret := _m.ctrl.Call(_m, "PutScalingPolicyRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.PutScalingPolicyOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) PutScalingPolicyRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "PutScalingPolicyRequest", arg0)
}

func (_m *MockAutoScalingAPI) PutScalingPolicy(_param0 *autoscaling.PutScalingPolicyInput) (*autoscaling.PutScalingPolicyOutput, error) {
	ret := _m.ctrl.Call(_m, "PutScalingPolicy", _param0)
	ret0, _ := ret[0].(*autoscaling.PutScalingPolicyOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) PutScalingPolicy(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "PutScalingPolicy", arg0)
}

func (_m *MockAutoScalingAPI) PutScheduledUpdateGroupActionRequest(_param0 *autoscaling.PutScheduledUpdateGroupActionInput) (*request.Request, *autoscaling.PutScheduledUpdateGroupActionOutput) {
	ret := _m.ctrl.Call(_m, "PutScheduledUpdateGroupActionRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.PutScheduledUpdateGroupActionOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) PutScheduledUpdateGroupActionRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "PutScheduledUpdateGroupActionRequest", arg0)
}

func (_m *MockAutoScalingAPI) PutScheduledUpdateGroupAction(_param0 *autoscaling.PutScheduledUpdateGroupActionInput) (*autoscaling.PutScheduledUpdateGroupActionOutput, error) {
	ret := _m.ctrl.Call(_m, "PutScheduledUpdateGroupAction", _param0)
	ret0, _ := ret[0].(*autoscaling.PutScheduledUpdateGroupActionOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) PutScheduledUpdateGroupAction(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "PutScheduledUpdateGroupAction", arg0)
}

func (_m *MockAutoScalingAPI) RecordLifecycleActionHeartbeatRequest(_param0 *autoscaling.RecordLifecycleActionHeartbeatInput) (*request.Request, *autoscaling.RecordLifecycleActionHeartbeatOutput) {
	ret := _m.ctrl.Call(_m, "RecordLifecycleActionHeartbeatRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.RecordLifecycleActionHeartbeatOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) RecordLifecycleActionHeartbeatRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "RecordLifecycleActionHeartbeatRequest", arg0)
}

func (_m *MockAutoScalingAPI) RecordLifecycleActionHeartbeat(_param0 *autoscaling.RecordLifecycleActionHeartbeatInput) (*autoscaling.RecordLifecycleActionHeartbeatOutput, error) {
	ret := _m.ctrl.Call(_m, "RecordLifecycleActionHeartbeat", _param0)
	ret0, _ := ret[0].(*autoscaling.RecordLifecycleActionHeartbeatOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) RecordLifecycleActionHeartbeat(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "RecordLifecycleActionHeartbeat", arg0)
}

func (_m *MockAutoScalingAPI) ResumeProcessesRequest(_param0 *autoscaling.ScalingProcessQuery) (*request.Request, *autoscaling.ResumeProcessesOutput) {
	ret := _m.ctrl.Call(_m, "ResumeProcessesRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.ResumeProcessesOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) ResumeProcessesRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ResumeProcessesRequest", arg0)
}

func (_m *MockAutoScalingAPI) ResumeProcesses(_param0 *autoscaling.ScalingProcessQuery) (*autoscaling.ResumeProcessesOutput, error) {
	ret := _m.ctrl.Call(_m, "ResumeProcesses", _param0)
	ret0, _ := ret[0].(*autoscaling.ResumeProcessesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) ResumeProcesses(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ResumeProcesses", arg0)
}

func (_m *MockAutoScalingAPI) SetDesiredCapacityRequest(_param0 *autoscaling.SetDesiredCapacityInput) (*request.Request, *autoscaling.SetDesiredCapacityOutput) {
	ret := _m.ctrl.Call(_m, "SetDesiredCapacityRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.SetDesiredCapacityOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) SetDesiredCapacityRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetDesiredCapacityRequest", arg0)
}

func (_m *MockAutoScalingAPI) SetDesiredCapacity(_param0 *autoscaling.SetDesiredCapacityInput) (*autoscaling.SetDesiredCapacityOutput, error) {
	ret := _m.ctrl.Call(_m, "SetDesiredCapacity", _param0)
	ret0, _ := ret[0].(*autoscaling.SetDesiredCapacityOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) SetDesiredCapacity(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetDesiredCapacity", arg0)
}

func (_m *MockAutoScalingAPI) SetInstanceHealthRequest(_param0 *autoscaling.SetInstanceHealthInput) (*request.Request, *autoscaling.SetInstanceHealthOutput) {
	ret := _m.ctrl.Call(_m, "SetInstanceHealthRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.SetInstanceHealthOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) SetInstanceHealthRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetInstanceHealthRequest", arg0)
}

func (_m *MockAutoScalingAPI) SetInstanceHealth(_param0 *autoscaling.SetInstanceHealthInput) (*autoscaling.SetInstanceHealthOutput, error) {
	ret := _m.ctrl.Call(_m, "SetInstanceHealth", _param0)
	ret0, _ := ret[0].(*autoscaling.SetInstanceHealthOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) SetInstanceHealth(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetInstanceHealth", arg0)
}

func (_m *MockAutoScalingAPI) SetInstanceProtectionRequest(_param0 *autoscaling.SetInstanceProtectionInput) (*request.Request, *autoscaling.SetInstanceProtectionOutput) {
	ret := _m.ctrl.Call(_m, "SetInstanceProtectionRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.SetInstanceProtectionOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) SetInstanceProtectionRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetInstanceProtectionRequest", arg0)
}

func (_m *MockAutoScalingAPI) SetInstanceProtection(_param0 *autoscaling.SetInstanceProtectionInput) (*autoscaling.SetInstanceProtectionOutput, error) {
	ret := _m.ctrl.Call(_m, "SetInstanceProtection", _param0)
	ret0, _ := ret[0].(*autoscaling.SetInstanceProtectionOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) SetInstanceProtection(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetInstanceProtection", arg0)
}

func (_m *MockAutoScalingAPI) SuspendProcessesRequest(_param0 *autoscaling.ScalingProcessQuery) (*request.Request, *autoscaling.SuspendProcessesOutput) {
	ret := _m.ctrl.Call(_m, "SuspendProcessesRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.SuspendProcessesOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) SuspendProcessesRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SuspendProcessesRequest", arg0)
}

func (_m *MockAutoScalingAPI) SuspendProcesses(_param0 *autoscaling.ScalingProcessQuery) (*autoscaling.SuspendProcessesOutput, error) {
	ret := _m.ctrl.Call(_m, "SuspendProcesses", _param0)
	ret0, _ := ret[0].(*autoscaling.SuspendProcessesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) SuspendProcesses(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SuspendProcesses", arg0)
}

func (_m *MockAutoScalingAPI) TerminateInstanceInAutoScalingGroupRequest(_param0 *autoscaling.TerminateInstanceInAutoScalingGroupInput) (*request.Request, *autoscaling.TerminateInstanceInAutoScalingGroupOutput) {
	ret := _m.ctrl.Call(_m, "TerminateInstanceInAutoScalingGroupRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.TerminateInstanceInAutoScalingGroupOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) TerminateInstanceInAutoScalingGroupRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "TerminateInstanceInAutoScalingGroupRequest", arg0)
}

func (_m *MockAutoScalingAPI) TerminateInstanceInAutoScalingGroup(_param0 *autoscaling.TerminateInstanceInAutoScalingGroupInput) (*autoscaling.TerminateInstanceInAutoScalingGroupOutput, error) {
	ret := _m.ctrl.Call(_m, "TerminateInstanceInAutoScalingGroup", _param0)
	ret0, _ := ret[0].(*autoscaling.TerminateInstanceInAutoScalingGroupOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) TerminateInstanceInAutoScalingGroup(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "TerminateInstanceInAutoScalingGroup", arg0)
}

func (_m *MockAutoScalingAPI) UpdateAutoScalingGroupRequest(_param0 *autoscaling.UpdateAutoScalingGroupInput) (*request.Request, *autoscaling.UpdateAutoScalingGroupOutput) {
	ret := _m.ctrl.Call(_m, "UpdateAutoScalingGroupRequest", _param0)
	ret0, _ := ret[0].(*request.Request)
	ret1, _ := ret[1].(*autoscaling.UpdateAutoScalingGroupOutput)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) UpdateAutoScalingGroupRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "UpdateAutoScalingGroupRequest", arg0)
}

func (_m *MockAutoScalingAPI) UpdateAutoScalingGroup(_param0 *autoscaling.UpdateAutoScalingGroupInput) (*autoscaling.UpdateAutoScalingGroupOutput, error) {
	ret := _m.ctrl.Call(_m, "UpdateAutoScalingGroup", _param0)
	ret0, _ := ret[0].(*autoscaling.UpdateAutoScalingGroupOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoScalingAPIRecorder) UpdateAutoScalingGroup(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "UpdateAutoScalingGroup", arg0)
}

func (_m *MockAutoScalingAPI) WaitUntilGroupExists(_param0 *autoscaling.DescribeAutoScalingGroupsInput) error {
	ret := _m.ctrl.Call(_m, "WaitUntilGroupExists", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockAutoScalingAPIRecorder) WaitUntilGroupExists(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "WaitUntilGroupExists", arg0)
}

func (_m *MockAutoScalingAPI) WaitUntilGroupInService(_param0 *autoscaling.DescribeAutoScalingGroupsInput) error {
	ret := _m.ctrl.Call(_m, "WaitUntilGroupInService", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockAutoScalingAPIRecorder) WaitUntilGroupInService(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "WaitUntilGroupInService", arg0)
}

func (_m *MockAutoScalingAPI) WaitUntilGroupNotExists(_param0 *autoscaling.DescribeAutoScalingGroupsInput) error {
	ret := _m.ctrl.Call(_m, "WaitUntilGroupNotExists", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockAutoScalingAPIRecorder) WaitUntilGroupNotExists(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "WaitUntilGroupNotExists", arg0)
}
